language: node_js

services:
  - docker

node_js:
  - 'node'

sudo: false

os:
  - linux

install:
  - npm ci
  - git submodule update --init

script:
  # Download base image only
  - npm run libdragon -- download
  # Build and install libdragon & mikmod - test docker script & build
  - npm run libdragon -- buildDragon
  # Test builds to check if they are also working propoerly
  - npm run libdragon -- make libdragon-install
  - npm run libdragon -- make -C ./libdragon-source tools-install
  # Test if examples are building properly through the container
  - npm run libdragon -- make examples
  # install dependencies to make sure they don't error out
  - npm run libdragon -- install
  # Test if test bench is building properly through the container
  - npm run build
  # Test if test suite is building properly through the container
  - npm run libdragon -- make tests

deploy:
  skip_cleanup: true
  provider: script
  script: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}" && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && npm publish
  on:
    branch: master
    repo: anacierdem/libdragon-docker
