language: node_js

services:
  - docker

node_js:
  - 'node'

sudo: false

os:
  - linux

install:
  - npm ci
  - git submodule update --init

script:
  # Download base image only
  - npm run download
  # Build and install libdragon & mikmod - test docker script & build
  - npm run buildDragon
  # Test NPM scripts to check if they are also working propoerly
  - npm run make -- -C ./libdragon-source
  - npm run make -- -C ./libdragon-source install
  - npm run make -- -C ./libdragon-source tools
  - npm run make -- -C ./libdragon-source tools-install
  # Test if examples are building properly through the container
  - npm run make -- -C ./libdragon-source examples
  - npm run dragonInstall
  # Test if test bench is building properly through the container
  - npm run build

deploy:
  skip_cleanup: true
  provider: script
  script: npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}" && echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && npm publish
  on:
    branch: master
    repo: anacierdem/libdragon-docker
