name: Build

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: npm ci

      - name: Test
        run: |
          npm run format-check
          npm run lint-check

  ci-basic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: npm ci

      - name: Test
        run: |
          npm run libdragon -- --verbose init
          npm run libdragon -- --verbose make clean
          npm run libdragon -- --verbose make bench
          npm run libdragon -- --verbose make examples
          npm run libdragon -- --verbose make tests
          npm run libdragon -- --verbose help

  ci-start-stop-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: npm ci

      - name: Test
        run: |
          npm run libdragon -- --verbose init
          npm run libdragon -- --verbose stop
          npm run libdragon -- --verbose start
          npm run libdragon -- --verbose update
          npm run libdragon -- --verbose install

  ci-no-git-make-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: |
          npm ci
          rm -rf ./libdragon
          rm -rf .git

      - name: Test
        run: |
          npm run libdragon -- --verbose init
          npm run libdragon -- --verbose make
          npm run libdragon -- --verbose update
          npm run libdragon -- --verbose install

  ci-pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: npm ci

      - name: Test release
        run: npm run pack