name: Github Release

on:
  push

jobs:
  Release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: npm ci

      - name: Package
        run: |
          npm run pack
          tar --transform='s/-linux//' -cvzf libdragon-linux-x86_64.tar.gz libdragon-linux
          tar --transform='s/-macos//' -cvzf libdragon-macos-x86_64.tar.gz libdragon-macos
          mv libdragon-win.exe libdragon.exe
          zip libdragon-win-x86_64.zip libdragon.exe

      - name: Release executable
        uses: softprops/action-gh-release@v1
        with:
          files: |
            libdragon-linux-x86_64.tar.gz
            libdragon-macos-x86_64.tar.gz
            libdragon-win-x86_64.zip
          prerelease: ${{ endsWith(github.ref, 'pre') }}