on:
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Test
        run: |
          npm run format-check
          npm run lint-check
          npm run tsc

  ci-tests:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Install Docker
        if: matrix.os == 'macos-latest'
        run: |
          brew install colima

      - name: Tests
        run: |
          git config --global user.name "libdragon-cli"
          git config --global user.email "cli@libdragon.dev"
          npm run test

  ci-pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Test release
        run: npm run pack
