on:
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: npm ci

      - name: Test
        run: |
          npm run format-check
          npm run lint-check
          npm run tsc

  ci-basic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: npm ci

      - name: Test
        run: |
          npm run libdragon -- --verbose init
          npm run libdragon -- --verbose make
          npm run libdragon -- --verbose exec ls
          npm run libdragon -- --verbose stop
          npm run libdragon -- --verbose start
          npm run libdragon -- --verbose update
          npm run libdragon -- --verbose install
          npm run libdragon -- --verbose --file=./src/build/test_bench.elf disasm main
          npm run libdragon -- --verbose destroy
          npm run libdragon -- --verbose help
          npm run libdragon -- --verbose version
          npm run libdragon -- --verbose init -s submodule

  ci-clean-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: |
          npm ci
          rm -rf libdragon
          rm -rf .libdragon
          rm -rf .git

      - name: Test
        run: |
          npm run libdragon -- --verbose init
          rm .git/libdragon-docker-container
          npm run libdragon -- --verbose make
          rm .git/libdragon-docker-container
          npm run libdragon -- --verbose update
          rm .git/libdragon-docker-container
          npm run libdragon -- --verbose install
          rm .git/libdragon-docker-container
          npm run libdragon -- --verbose --file=./src/build/test_bench.elf disasm main
          rm .git/libdragon-docker-container
          npm run libdragon -- --verbose destroy

  ci-manual:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: |
          npm ci
          mv libdragon libdragon_test

      - name: Test
        run: |
          npm run libdragon -- --verbose init -s manual -d ./libdragon_test
          npm run libdragon -- --verbose exec ls
          npm run libdragon -- --verbose stop
          npm run libdragon -- --verbose start
          npm run libdragon -- --verbose update
          npm run libdragon -- --verbose install
          npm run libdragon -- --verbose destroy
          npm run libdragon -- --verbose help
          npm run libdragon -- --verbose version
          npm run libdragon -- --verbose init -s manual -d ./libdragon_test

  ci-subtree:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: |
          npm ci
          rm -rf libdragon
          rm -rf .libdragon
          rm -rf .git
          git config --global user.name "libdragon-cli"
          git config --global user.email "cli@libdragon.dev"

      - name: Test
        run: |
          npm run libdragon -- --verbose init -s subtree -d ./libdragon
          npm run libdragon -- --verbose make
          npm run libdragon -- --verbose exec ls
          npm run libdragon -- --verbose stop
          npm run libdragon -- --verbose start
          npm run libdragon -- --verbose update
          npm run libdragon -- --verbose install
          npm run libdragon -- --verbose --file=./src/build/test_bench.elf disasm main
          npm run libdragon -- --verbose destroy
          npm run libdragon -- --verbose help
          npm run libdragon -- --verbose version
          npm run libdragon -- --verbose init -s subtree -d ./libdragon

  ci-pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: npm ci

      - name: Test release
        run: npm run pack
