on:
  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: npm ci

      - name: Test
        run: |
          npm run format-check
          npm run lint-check
          npm run tsc
          git config --global user.name "libdragon-cli"
          git config --global user.email "cli@libdragon.dev"
          npm run test

  ci-pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: npm ci

      - name: Test release
        run: npm run pack
